name: Mirror Main to HF

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF Space (chatbot)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://fzanartu:${HF_TOKEN}@huggingface.co/spaces/skepticalscience/chatbot
          git push hf main:main --force
