name: Mirror Inoculation to HF

on:
  push:
    branches:
      - feature/inoculation

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF Space (typical-inoculation-chatbot)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://fzanartu:${HF_TOKEN}@huggingface.co/spaces/skepticalscience/typical-inoculation-chatbot
          git push hf feature/inoculation:main --force
